server:
  port: 8082
spring:
  application:
    name: InvoiceService
  datasource:
    url: jdbc:mysql://localhost:3306/factuexpress
    username: factuexpress
    password: 12345
  jpa:
    show-sql: true